/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus.test;

import java.util.Arrays;

/**
 * Builds the answers of a well behaved Modbus slave. Coils and discrete inputs
 * always read as set, register n reads as n + 1.
 */
public final class ModbusSlave {

    private ModbusSlave() {
    }

    public static byte[] reply(byte[] request) {
        byte unit = request[0];
        byte function = request[1];

        switch (function) {
        case 1:
        case 2:
            return readBits(unit, function, count(request));
        case 3:
        case 4:
            return readRegisters(unit, function, count(request));
        case 5:
        case 6:
        case 15:
        case 16:
            // the slave echoes the header of a write command
            return Arrays.copyOf(request, 6);
        default:
            return illegalFunction(unit, function);
        }
    }

    /** Answers as if a different unit had been addressed. */
    public static byte[] fromAnotherUnit(byte[] request) {
        byte[] response = reply(request);
        response[0] = (byte) (request[0] + 1);
        return response;
    }

    /** Answers every request with the "illegal function" exception. */
    public static byte[] refuse(byte[] request) {
        return illegalFunction(request[0], request[1]);
    }

    private static byte[] illegalFunction(byte unit, byte function) {
        return new byte[] { unit, (byte) (function | 0x80), 0x01 };
    }

    private static int count(byte[] request) {
        return ((request[4] & 0xff) << 8) + (request[5] & 0xff);
    }

    private static byte[] readBits(byte unit, byte function, int count) {
        int byteCount = (count + 7) / 8;
        byte[] response = new byte[3 + byteCount];
        response[0] = unit;
        response[1] = function;
        response[2] = (byte) byteCount;
        for (int i = 0; i < byteCount; i++) {
            response[3 + i] = (byte) 0xff;
        }
        return response;
    }

    private static byte[] readRegisters(byte unit, byte function, int count) {
        byte[] response = new byte[3 + count * 2];
        response[0] = unit;
        response[1] = function;
        response[2] = (byte) (count * 2);
        for (int i = 0; i < count; i++) {
            response[3 + i * 2] = (byte) ((i + 1) >> 8);
            response[4 + i * 2] = (byte) (i + 1);
        }
        return response;
    }
}
