/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class Crc16Test {

    private static final int SEED = 0x0ffff;

    @Test
    public void shouldComputeTheCrcOfAReadHoldingRegistersRequest() {
        givenBuffer(0x01, 0x03, 0x00, 0x00, 0x00, 0x01);

        whenTheCrcIsComputed();

        thenTheCrcIs(0x0A84);
    }

    @Test
    public void shouldComputeTheCrcOfAReadCoilsRequest() {
        givenBuffer(0x01, 0x01, 0x00, 0x00, 0x00, 0x01);

        whenTheCrcIsComputed();

        thenTheCrcIs(0xCAFD);
    }

    @Test
    public void shouldNotReportAnErrorOnAFrameThatCarriesItsOwnCrc() {
        givenBuffer(0x01, 0x03, 0x00, 0x00, 0x00, 0x01);
        givenTheCrcIsAppendedToTheBuffer();

        whenTheCrcIsComputed();

        thenTheCrcIs(0);
    }

    @Test
    public void shouldReturnTheSeedForAnEmptyBuffer() {
        givenBuffer();

        whenTheCrcIsComputed();

        thenTheCrcIs(SEED);
    }

    @Test
    public void shouldOnlyConsiderTheRequestedNumberOfBytes() {
        givenBuffer(0x01, 0x03, 0x7f, 0x7f);
        givenOnlyTheFirstBytesAreConsidered(2);

        whenTheCrcIsComputed();

        thenTheCrcIsTheSameAsForTheBuffer(0x01, 0x03);
    }

    private byte[] buffer;
    private int length;
    private int crc;

    private void givenBuffer(int... bytes) {
        this.buffer = new byte[bytes.length];
        for (int i = 0; i < bytes.length; i++) {
            this.buffer[i] = (byte) bytes[i];
        }
        this.length = bytes.length;
    }

    private void givenTheCrcIsAppendedToTheBuffer() {
        int computed = Crc16.getCrc16(this.buffer, this.length, SEED);

        byte[] frame = new byte[this.length + 2];
        System.arraycopy(this.buffer, 0, frame, 0, this.length);
        frame[this.length] = (byte) computed;
        frame[this.length + 1] = (byte) (computed >> 8);

        this.buffer = frame;
        this.length = frame.length;
    }

    private void givenOnlyTheFirstBytesAreConsidered(int count) {
        this.length = count;
    }

    private void whenTheCrcIsComputed() {
        this.crc = Crc16.getCrc16(this.buffer, this.length, SEED);
    }

    private void thenTheCrcIs(int expected) {
        assertEquals(expected, this.crc);
    }

    private void thenTheCrcIsTheSameAsForTheBuffer(int... bytes) {
        byte[] other = new byte[bytes.length];
        for (int i = 0; i < bytes.length; i++) {
            other[i] = (byte) bytes[i];
        }

        assertEquals(Crc16.getCrc16(other, other.length, SEED), this.crc);
    }
}
