/*******************************************************************************
 * Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 ******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.util.Properties;

import org.eclipse.kura.KuraConnectionStatus;
import org.eclipse.kura.protocol.modbus.test.ModbusServer;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Feature: exchanging Modbus messages with a slave over Modbus TCP. The failure
 * paths of the same transport are covered by {@link TcpTransactionFailureTest}.
 */
public class ModbusProtocolDeviceTest {

    @Test
    public void shouldReportTheConnectionAsEstablished() {
        givenAConnectedDevice();

        whenTheConnectionStatusIsRead();

        thenTheReadStatusIs(KuraConnectionStatus.CONNECTED);
    }

    @Test
    public void shouldReadACoil() {
        givenAConnectedDevice();

        whenCoilsAreRead(0, 1);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true);
    }

    @Test
    public void shouldReadDiscreteInputs() {
        givenAConnectedDevice();

        whenDiscreteInputsAreRead(1, 4);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, true, true, true);
    }

    @Test
    public void shouldReadAHoldingRegister() {
        givenAConnectedDevice();

        whenHoldingRegistersAreRead(0, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(2);
    }

    @Test
    public void shouldReadAnInputRegister() {
        givenAConnectedDevice();

        whenInputRegistersAreRead(8, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(10);
    }

    @Test
    public void shouldWriteASingleCoil() {
        givenAConnectedDevice();

        whenASingleCoilIsWritten(0, true);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteMultipleCoils() {
        givenAConnectedDevice();

        whenMultipleCoilsAreWritten(1, true, false, true, true, false);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteASingleRegister() {
        givenAConnectedDevice();

        whenASingleRegisterIsWritten(0, 37);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteMultipleRegisters() {
        givenAConnectedDevice();

        whenMultipleRegistersAreWritten(0, 12, 24, 46, 58);

        thenNoFailureIsReported();
    }

    private static final Logger logger = LoggerFactory.getLogger(ModbusProtocolDeviceTest.class);

    private static final int PORT = 32345;
    private static final int UNIT = 1;

    private static ModbusServer modbusServer;

    private ModbusProtocolDevice device;
    private ModbusProtocolException failure;
    private boolean[] readBooleans;
    private int[] readRegisters;
    private int connectionStatus;

    @BeforeClass
    public static void startServer() throws Exception {
        modbusServer = new ModbusServer();
        modbusServer.start(PORT);
        logger.info("MODBUS server started");
    }

    @AfterClass
    public static void stopServer() throws IOException {
        modbusServer.stop();
        logger.info("MODBUS server stopped");
    }

    @After
    public void disconnect() throws ModbusProtocolException {
        this.device.disconnect();
    }

    private void givenAConnectedDevice() {
        Properties connectionConfig = new Properties();
        connectionConfig.setProperty("connectionType", ModbusProtocolDevice.PROTOCOL_CONNECTION_TYPE_ETHER_TCP);
        connectionConfig.setProperty("ipAddress", "127.0.0.1");
        connectionConfig.setProperty("ethport", Integer.toString(PORT));
        connectionConfig.setProperty("respTimeout", "10000");
        connectionConfig.setProperty("transmissionMode", ModbusTransmissionMode.RTU);

        this.device = new ModbusProtocolDevice();
        try {
            this.device.configureConnection(connectionConfig);
            this.device.connect();
        } catch (ModbusProtocolException e) {
            fail("the connection could not be opened: " + e.getMessage());
        }
    }

    private void whenTheConnectionStatusIsRead() {
        this.connectionStatus = this.device.getConnectStatus();
    }

    private void whenCoilsAreRead(int dataAddress, int count) {
        try {
            this.readBooleans = this.device.readCoils(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenDiscreteInputsAreRead(int dataAddress, int count) {
        try {
            this.readBooleans = this.device.readDiscreteInputs(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenHoldingRegistersAreRead(int dataAddress, int count) {
        try {
            this.readRegisters = this.device.readHoldingRegisters(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenInputRegistersAreRead(int dataAddress, int count) {
        try {
            this.readRegisters = this.device.readInputRegisters(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleCoilIsWritten(int dataAddress, boolean value) {
        try {
            this.device.writeSingleCoil(UNIT, dataAddress, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleCoilsAreWritten(int dataAddress, boolean... values) {
        try {
            this.device.writeMultipleCoils(UNIT, dataAddress, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleRegisterIsWritten(int dataAddress, int value) {
        try {
            this.device.writeSingleRegister(UNIT, dataAddress, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleRegistersAreWritten(int dataAddress, int... values) {
        try {
            this.device.writeMultipleRegister(UNIT, dataAddress, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void thenNoFailureIsReported() {
        if (this.failure != null) {
            fail("unexpected failure: " + this.failure.getMessage());
        }
    }

    private void thenTheReadStatusIs(int expected) {
        assertEquals(expected, this.connectionStatus);
    }

    private void thenTheReadBooleansAre(boolean... expected) {
        assertArrayEquals(expected, this.readBooleans);
    }

    private void thenTheReadRegistersAre(int... expected) {
        assertArrayEquals(expected, this.readRegisters);
    }
}
