/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertTrue;

import org.eclipse.kura.protocol.modbus.test.ModbusSlave;
import org.eclipse.kura.protocol.modbus.test.SerialSlave.Fault;
import org.junit.After;
import org.junit.Test;

/**
 * Feature: exchanging Modbus messages with a slave over a serial port, in both
 * RTU and ASCII transmission mode.
 */
public class SerialTransactionTest extends AbstractSerialFeature {

    @Test
    public void shouldReadHoldingRegistersInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 3);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(1, 2, 3);
    }

    @Test
    public void shouldReadInputRegistersInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenInputRegistersAreRead(4, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(1);
    }

    @Test
    public void shouldReadCoilsInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenCoilsAreRead(0, 3);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, true, true);
    }

    @Test
    public void shouldReadDiscreteInputsInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenDiscreteInputsAreRead(0, 2);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, true);
    }

    @Test
    public void shouldWriteASingleCoilInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenASingleCoilIsWritten(3, true);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteASingleRegisterInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenASingleRegisterIsWritten(3, 0x1234);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteMultipleCoilsInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenMultipleCoilsAreWritten(0, true, false, true);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldWriteMultipleRegistersInRtuMode() {
        givenAnRtuSlave();
        givenAnOpenConnection();

        whenMultipleRegistersAreWritten(0, 1, 2);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldReadHoldingRegistersInAsciiMode() {
        givenAnAsciiSlave();
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 2);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(1, 2);
    }

    @Test
    public void shouldReadCoilsInAsciiMode() {
        givenAnAsciiSlave();
        givenAnOpenConnection();

        whenCoilsAreRead(0, 2);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, true);
    }

    @Test
    public void shouldWriteASingleRegisterInAsciiMode() {
        givenAnAsciiSlave();
        givenAnOpenConnection();

        whenASingleRegisterIsWritten(1, 7);

        thenNoFailureIsReported();
    }

    @Test
    public void shouldFlushStaleBytesBeforeTheNextTransaction() {
        givenAnRtuSlaveWith(Fault.EXTRA_BYTES);
        givenAnOpenConnection();

        whenHoldingRegistersAreReadTwice(0, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(1);
    }

    @Test
    public void shouldReportAnExceptionResponse() {
        givenASlave(ModbusTransmissionMode.RTU, ModbusSlave::refuse, Fault.NONE);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("Exception response");
    }

    @Test
    public void shouldTimeOutWhenTheSlaveStaysSilent() {
        givenAnRtuSlaveWith(Fault.SILENT);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.RESPONSE_TIMEOUT);
    }

    @Test
    public void shouldDiscardAReadResponseWithABadCrc() {
        givenAnRtuSlaveWith(Fault.BAD_CHECKSUM);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.RESPONSE_TIMEOUT);
    }

    @Test
    public void shouldDiscardAWriteEchoWithABadCrc() {
        givenAnRtuSlaveWith(Fault.BAD_CHECKSUM);
        givenAnOpenConnection();

        whenASingleRegisterIsWritten(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.RESPONSE_TIMEOUT);
    }

    @Test
    public void shouldDiscardAnExceptionResponseWithABadCrc() {
        givenASlave(ModbusTransmissionMode.RTU, ModbusSlave::refuse, Fault.BAD_CHECKSUM);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.RESPONSE_TIMEOUT);
    }

    @Test
    public void shouldRejectAnAsciiResponseWithABadLrc() {
        givenAnAsciiSlaveWith(Fault.BAD_CHECKSUM);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("Bad LRC");
    }

    @Test
    public void shouldIgnoreBytesThatDoNotOpenAFrame() {
        givenASlave(ModbusTransmissionMode.RTU, ModbusSlave::fromAnotherUnit, Fault.NONE);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.RESPONSE_TIMEOUT);
    }

    @Test
    public void shouldFailWhenTheStreamEndsMidFrame() {
        givenAnRtuSlaveWith(Fault.END_OF_STREAM);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("End of stream");
    }

    @Test
    public void shouldReportAFailureToWriteTheRequest() {
        givenAnRtuSlaveWith(Fault.WRITE_ERROR);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
    }

    @Test
    public void shouldGiveUpWhenTheThreadIsInterrupted() {
        givenAnRtuSlaveWith(Fault.SILENT);
        givenAnOpenConnection();
        givenTheCurrentThreadIsInterrupted();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("Thread interrupted");
        thenTheInterruptIsStillPending();
    }

    private boolean[] readBooleans;
    private int[] readRegisters;

    @After
    public void clearTheInterruptFlag() {
        Thread.interrupted();
    }

    private void givenTheCurrentThreadIsInterrupted() {
        Thread.currentThread().interrupt();
    }

    private void whenCoilsAreRead(int dataAddress, int count) {
        try {
            this.readBooleans = this.device.readCoils(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenDiscreteInputsAreRead(int dataAddress, int count) {
        try {
            this.readBooleans = this.device.readDiscreteInputs(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenHoldingRegistersAreRead(int dataAddress, int count) {
        try {
            this.readRegisters = this.device.readHoldingRegisters(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenHoldingRegistersAreReadTwice(int dataAddress, int count) {
        whenHoldingRegistersAreRead(dataAddress, count);
        whenHoldingRegistersAreRead(dataAddress, count);
    }

    private void whenInputRegistersAreRead(int dataAddress, int count) {
        try {
            this.readRegisters = this.device.readInputRegisters(UNIT, dataAddress, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleCoilIsWritten(int dataAddress, boolean value) {
        try {
            this.device.writeSingleCoil(UNIT, dataAddress, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleRegisterIsWritten(int dataAddress, int value) {
        try {
            this.device.writeSingleRegister(UNIT, dataAddress, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleCoilsAreWritten(int dataAddress, boolean... values) {
        try {
            this.device.writeMultipleCoils(UNIT, dataAddress, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleRegistersAreWritten(int dataAddress, int... values) {
        try {
            this.device.writeMultipleRegister(UNIT, dataAddress, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void thenTheReadBooleansAre(boolean... expected) {
        assertArrayEquals(expected, this.readBooleans);
    }

    private void thenTheReadRegistersAre(int... expected) {
        assertArrayEquals(expected, this.readRegisters);
    }

    private void thenTheInterruptIsStillPending() {
        assertTrue(Thread.currentThread().isInterrupted());
    }
}
