/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus.integration;

import java.io.DataInputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A Modbus TCP slave listening on a local port, holding a small register and
 * coil bank. Writes update the bank and reads serve it, so a test can check a
 * full round trip through the driver.
 */
public class ModbusTcpSlave implements AutoCloseable {

    private static final Logger logger = LoggerFactory.getLogger(ModbusTcpSlave.class);

    /** How the slave should answer. */
    public enum Behaviour {
        NORMAL,
        /** Read the request and never answer. */
        SILENT,
        /** Answer every request with the "illegal data address" exception. */
        EXCEPTION
    }

    private static final int MBAP_LENGTH = 6;
    private static final int BANK_SIZE = 64;
    private static final byte ILLEGAL_DATA_ADDRESS = 0x02;

    private final ServerSocket serverSocket;
    private final Thread thread;
    private final int[] registers = new int[BANK_SIZE];
    private final boolean[] coils = new boolean[BANK_SIZE];

    private volatile Behaviour behaviour = Behaviour.NORMAL;
    private volatile boolean listening = true;

    public ModbusTcpSlave() throws IOException {
        this.serverSocket = new ServerSocket(0);
        this.thread = new Thread(this::serve, "ModbusTcpSlave");
        this.thread.setDaemon(true);
        this.thread.start();
    }

    public int getPort() {
        return this.serverSocket.getLocalPort();
    }

    public void setBehaviour(Behaviour behaviour) {
        this.behaviour = behaviour;
    }

    public void setRegister(int address, int value) {
        this.registers[address] = value;
    }

    public int getRegister(int address) {
        return this.registers[address];
    }

    public void setCoil(int address, boolean value) {
        this.coils[address] = value;
    }

    public boolean getCoil(int address) {
        return this.coils[address];
    }

    @Override
    public void close() throws IOException {
        this.listening = false;
        this.serverSocket.close();
    }

    private void serve() {
        while (this.listening) {
            try (Socket socket = this.serverSocket.accept()) {
                exchange(socket);
            } catch (IOException e) {
                if (this.listening) {
                    logger.debug("ModbusTcpSlave stopped serving", e);
                }
                return;
            }
        }
    }

    private void exchange(Socket socket) throws IOException {
        DataInputStream in = new DataInputStream(socket.getInputStream());
        OutputStream out = socket.getOutputStream();

        while (this.listening) {
            byte[] header = new byte[MBAP_LENGTH];
            try {
                in.readFully(header);
            } catch (EOFException e) {
                return;
            }

            byte[] pdu = new byte[((header[4] & 0xff) << 8) + (header[5] & 0xff)];
            in.readFully(pdu);

            if (this.behaviour == Behaviour.SILENT) {
                continue;
            }

            byte[] answer = this.behaviour == Behaviour.EXCEPTION ? exception(pdu) : handle(pdu);
            out.write(frame(header, answer));
            out.flush();
        }
    }

    /**
     * Wraps a PDU in the MBAP header, echoing back the transaction identifier.
     */
    private static byte[] frame(byte[] requestHeader, byte[] pdu) {
        byte[] response = new byte[MBAP_LENGTH + pdu.length];
        response[0] = requestHeader[0];
        response[1] = requestHeader[1];
        response[2] = 0;
        response[3] = 0;
        response[4] = (byte) (pdu.length >> 8);
        response[5] = (byte) pdu.length;
        System.arraycopy(pdu, 0, response, MBAP_LENGTH, pdu.length);
        return response;
    }

    private static byte[] exception(byte[] pdu) {
        return new byte[] { pdu[0], (byte) (pdu[1] | 0x80), ILLEGAL_DATA_ADDRESS };
    }

    private byte[] handle(byte[] pdu) {
        byte unit = pdu[0];
        byte function = pdu[1];
        int address = word(pdu, 2);

        switch (function) {
        case 1:
        case 2:
            return readCoils(unit, function, address, word(pdu, 4));
        case 3:
        case 4:
            return readRegisters(unit, function, address, word(pdu, 4));
        case 5:
            this.coils[address] = (pdu[4] & 0xff) == 0xff;
            return echo(pdu, 6);
        case 6:
            this.registers[address] = word(pdu, 4);
            return echo(pdu, 6);
        case 15:
            writeCoils(pdu, address, word(pdu, 4));
            return echo(pdu, 6);
        case 16:
            writeRegisters(pdu, address, word(pdu, 4));
            return echo(pdu, 6);
        default:
            return exception(pdu);
        }
    }

    private byte[] readCoils(byte unit, byte function, int address, int count) {
        int byteCount = (count + 7) / 8;
        byte[] pdu = new byte[3 + byteCount];
        pdu[0] = unit;
        pdu[1] = function;
        pdu[2] = (byte) byteCount;
        for (int i = 0; i < count; i++) {
            if (this.coils[address + i]) {
                pdu[3 + i / 8] |= (byte) (1 << i % 8);
            }
        }
        return pdu;
    }

    private byte[] readRegisters(byte unit, byte function, int address, int count) {
        byte[] pdu = new byte[3 + count * 2];
        pdu[0] = unit;
        pdu[1] = function;
        pdu[2] = (byte) (count * 2);
        for (int i = 0; i < count; i++) {
            pdu[3 + i * 2] = (byte) (this.registers[address + i] >> 8);
            pdu[4 + i * 2] = (byte) this.registers[address + i];
        }
        return pdu;
    }

    private void writeCoils(byte[] pdu, int address, int count) {
        for (int i = 0; i < count; i++) {
            this.coils[address + i] = (pdu[7 + i / 8] & 1 << i % 8) != 0;
        }
    }

    private void writeRegisters(byte[] pdu, int address, int count) {
        for (int i = 0; i < count; i++) {
            this.registers[address + i] = word(pdu, 7 + i * 2);
        }
    }

    private static byte[] echo(byte[] pdu, int length) {
        byte[] answer = new byte[length];
        System.arraycopy(pdu, 0, answer, 0, length);
        return answer;
    }

    private static int word(byte[] data, int offset) {
        return ((data[offset] & 0xff) << 8) + (data[offset + 1] & 0xff);
    }
}
