/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.protocol.modbus.integration;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.util.Collection;
import java.util.Properties;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.KuraConnectionStatus;
import org.eclipse.kura.protocol.modbus.ModbusProtocolDeviceService;
import org.eclipse.kura.protocol.modbus.ModbusProtocolErrorCode;
import org.eclipse.kura.protocol.modbus.ModbusProtocolException;
import org.eclipse.kura.protocol.modbus.ModbusTransmissionMode;
import org.eclipse.kura.protocol.modbus.integration.ModbusTcpSlave.Behaviour;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Test;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleException;
import org.osgi.framework.ServiceReference;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Feature: the Modbus addon, once installed in a Kura framework, talks Modbus
 * TCP to a real slave.
 *
 * The bundle only reaches ACTIVE if every {@code Import-Package} range it
 * declares is satisfied by the framework, and the service is only published once
 * its mandatory references to the OSGi {@code ConnectionFactory} and to the Kura
 * {@code UsbService} are wired. Everything else is exercised end to end against
 * a slave listening on a local socket, so the assertions cover the framing on
 * the wire and not just the presence of the service.
 *
 * The service is looked up through the {@link BundleContext} instead of being
 * injected with {@code @Reference}: the Kura bundles carry no
 * {@code osgi.service} capability, so a Declarative Services reference to them
 * would make the bnd resolution of this bndrun fail.
 */
@Component(immediate = true)
public class ModbusProtocolDeviceServiceItTest {

    @Test
    public void shouldActivateTheBundleAndPublishTheService() {
        givenAnActivatedFramework();

        whenTheProtocolDeviceServiceIsLookedUp();

        thenTheServiceIsPublished();
        thenTheModbusBundleIsActive();
    }

    @Test
    public void shouldEstablishATcpConnection() {
        givenAnActivatedFramework();
        givenARunningSlave();

        whenTheConnectionToTheSlaveIsOpened();

        thenNoFailureIsReported();
        thenTheConnectionStatusIs(KuraConnectionStatus.CONNECTED);
    }

    @Test
    public void shouldReadHoldingRegisters() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveRegister(0, 11);
        givenTheSlaveRegister(1, 22);
        givenTheSlaveRegister(2, 0xBEEF);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 3);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(11, 22, 0xBEEF);
    }

    @Test
    public void shouldReadInputRegisters() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveRegister(7, 1234);
        givenAnOpenConnection();

        whenInputRegistersAreRead(7, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(1234);
    }

    @Test
    public void shouldReadCoils() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveCoil(0, true);
        givenTheSlaveCoil(1, false);
        givenTheSlaveCoil(2, true);
        givenAnOpenConnection();

        whenCoilsAreRead(0, 3);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, false, true);
    }

    @Test
    public void shouldReadDiscreteInputs() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveCoil(4, true);
        givenTheSlaveCoil(5, true);
        givenAnOpenConnection();

        whenDiscreteInputsAreRead(4, 2);

        thenNoFailureIsReported();
        thenTheReadBooleansAre(true, true);
    }

    @Test
    public void shouldWriteASingleRegister() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenASingleRegisterIsWritten(3, 0x1234);

        thenNoFailureIsReported();
        thenTheSlaveRegisterIs(3, 0x1234);
    }

    @Test
    public void shouldWriteMultipleRegisters() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenMultipleRegistersAreWritten(10, 1, 2, 3, 4);

        thenNoFailureIsReported();
        thenTheSlaveRegisterIs(10, 1);
        thenTheSlaveRegisterIs(11, 2);
        thenTheSlaveRegisterIs(12, 3);
        thenTheSlaveRegisterIs(13, 4);
    }

    @Test
    public void shouldWriteASingleCoil() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenASingleCoilIsWritten(9, true);

        thenNoFailureIsReported();
        thenTheSlaveCoilIs(9, true);
    }

    @Test
    public void shouldWriteMultipleCoils() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenMultipleCoilsAreWritten(16, true, false, true);

        thenNoFailureIsReported();
        thenTheSlaveCoilIs(16, true);
        thenTheSlaveCoilIs(17, false);
        thenTheSlaveCoilIs(18, true);
    }

    @Test
    public void shouldWriteAWholeByteOfCoils() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenMultipleCoilsAreWritten(24, true, true, true, true, true, true, true, true);

        thenNoFailureIsReported();
        thenTheSlaveCoilsAreSetFrom(24, 8);
    }

    @Test
    public void shouldReadBackWhatItHasWritten() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenASingleRegisterIsWritten(20, 4242);
        whenHoldingRegistersAreRead(20, 1);

        thenNoFailureIsReported();
        thenTheReadRegistersAre(4242);
    }

    @Test
    public void shouldReportAnExceptionRaisedByTheSlave() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveAnswersWithAnException();
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("Modbus responds an error");
    }

    @Test
    public void shouldTimeOutWhenTheSlaveDoesNotAnswer() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheSlaveStaysSilent();
        givenTheResponseTimeout(500);
        givenAnOpenConnection();

        whenHoldingRegistersAreRead(0, 1);

        thenTheFailureCodeIs(ModbusProtocolErrorCode.TRANSACTION_FAILURE);
        thenTheFailureMentions("Recv timeout");
    }

    @Test
    public void shouldRejectAnUnknownTransmissionMode() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenTheTransmissionMode("SMOKE_SIGNALS");

        whenTheConnectionToTheSlaveIsOpened();

        thenTheFailureCodeIs(ModbusProtocolErrorCode.INVALID_CONFIGURATION);
    }

    @Test
    public void shouldRefuseToReadAfterADisconnect() {
        givenAnActivatedFramework();
        givenARunningSlave();
        givenAnOpenConnection();

        whenTheConnectionIsClosed();
        whenHoldingRegistersAreRead(0, 1);

        thenTheConnectionStatusIs(KuraConnectionStatus.NEVERCONNECTED);
        thenTheFailureCodeIs(ModbusProtocolErrorCode.NOT_CONNECTED);
    }

    private static final Logger logger = LoggerFactory.getLogger(ModbusProtocolDeviceServiceItTest.class);

    private static final String MODBUS_BUNDLE = "org.eclipse.kura.protocol.modbus";
    private static final long TIMEOUT_SECONDS = 60;
    private static final int UNIT = 1;

    private static final CountDownLatch activated = new CountDownLatch(1);

    // needs to be static for being available to JUnit Runner
    private static BundleContext bundleContext;

    private ModbusProtocolDeviceService modbus;
    private ModbusTcpSlave slave;
    private String transmissionMode = ModbusTransmissionMode.RTU;
    private int responseTimeout = 3000;
    private ModbusProtocolException failure;
    private int[] readRegisters;
    private boolean[] readBooleans;

    @Activate
    public void activate(BundleContext context) {
        bundleContext = context;
        activated.countDown();
    }

    @After
    public void releaseTheConnection() throws IOException {
        if (this.modbus != null) {
            try {
                this.modbus.disconnect();
            } catch (ModbusProtocolException e) {
                logger.warn("could not release the connection", e);
            }
        }
        if (this.slave != null) {
            this.slave.close();
        }
    }

    @AfterClass
    public static void cleanup() {
        logger.info("Shutting down OSGi framework...");
        if (bundleContext != null) {
            try {
                Bundle systemBundle = bundleContext.getBundle(0);
                systemBundle.stop();
            } catch (BundleException e) {
                logger.error("Error stopping framework", e);
            }
        }
    }

    private void givenAnActivatedFramework() {
        try {
            if (!activated.await(TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                fail("the test component was not activated in " + TIMEOUT_SECONDS + " seconds");
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            fail("interrupted while waiting for the test component");
        }
    }

    private void givenARunningSlave() {
        try {
            this.slave = new ModbusTcpSlave();
        } catch (IOException e) {
            fail("the slave could not be started: " + e.getMessage());
        }
    }

    private void givenTheSlaveRegister(int address, int value) {
        this.slave.setRegister(address, value);
    }

    private void givenTheSlaveCoil(int address, boolean value) {
        this.slave.setCoil(address, value);
    }

    private void givenTheSlaveAnswersWithAnException() {
        this.slave.setBehaviour(Behaviour.EXCEPTION);
    }

    private void givenTheSlaveStaysSilent() {
        this.slave.setBehaviour(Behaviour.SILENT);
    }

    private void givenTheResponseTimeout(int milliseconds) {
        this.responseTimeout = milliseconds;
    }

    private void givenTheTransmissionMode(String mode) {
        this.transmissionMode = mode;
    }

    private void givenAnOpenConnection() {
        whenTheConnectionToTheSlaveIsOpened();
        if (this.failure != null) {
            fail("the connection could not be opened: " + this.failure.getMessage());
        }
    }

    private void whenTheProtocolDeviceServiceIsLookedUp() {
        this.modbus = awaitService(ModbusProtocolDeviceService.class);
    }

    private void whenTheConnectionToTheSlaveIsOpened() {
        whenTheProtocolDeviceServiceIsLookedUp();

        Properties config = new Properties();
        config.setProperty("connectionType", "TCP/IP");
        config.setProperty("transmissionMode", this.transmissionMode);
        config.setProperty("respTimeout", Integer.toString(this.responseTimeout));
        config.setProperty("ipAddress", "127.0.0.1");
        config.setProperty("ethport", Integer.toString(this.slave.getPort()));

        try {
            this.modbus.configureConnection(config);
            this.modbus.connect();
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenTheConnectionIsClosed() {
        try {
            this.modbus.disconnect();
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenHoldingRegistersAreRead(int address, int count) {
        try {
            this.readRegisters = this.modbus.readHoldingRegisters(UNIT, address, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenInputRegistersAreRead(int address, int count) {
        try {
            this.readRegisters = this.modbus.readInputRegisters(UNIT, address, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenCoilsAreRead(int address, int count) {
        try {
            this.readBooleans = this.modbus.readCoils(UNIT, address, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenDiscreteInputsAreRead(int address, int count) {
        try {
            this.readBooleans = this.modbus.readDiscreteInputs(UNIT, address, count);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleRegisterIsWritten(int address, int value) {
        try {
            this.modbus.writeSingleRegister(UNIT, address, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleRegistersAreWritten(int address, int... values) {
        try {
            this.modbus.writeMultipleRegister(UNIT, address, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenASingleCoilIsWritten(int address, boolean value) {
        try {
            this.modbus.writeSingleCoil(UNIT, address, value);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void whenMultipleCoilsAreWritten(int address, boolean... values) {
        try {
            this.modbus.writeMultipleCoils(UNIT, address, values);
        } catch (ModbusProtocolException e) {
            this.failure = e;
        }
    }

    private void thenTheServiceIsPublished() {
        assertNotNull(this.modbus);
    }

    private void thenTheModbusBundleIsActive() {
        for (Bundle bundle : bundleContext.getBundles()) {
            if (MODBUS_BUNDLE.equals(bundle.getSymbolicName())) {
                assertEquals("the " + MODBUS_BUNDLE + " bundle is not active", Bundle.ACTIVE, bundle.getState());
                return;
            }
        }
        fail("the " + MODBUS_BUNDLE + " bundle is not installed");
    }

    private void thenNoFailureIsReported() {
        if (this.failure != null) {
            fail("unexpected failure: " + this.failure.getMessage());
        }
    }

    private void thenTheFailureCodeIs(ModbusProtocolErrorCode expected) {
        assertNotNull("no failure was reported", this.failure);
        assertEquals(expected, this.failure.getCode());
    }

    private void thenTheFailureMentions(String text) {
        assertNotNull("no failure was reported", this.failure);
        assertTrue(this.failure.getMessage().contains(text));
    }

    private void thenTheConnectionStatusIs(int expected) {
        assertEquals(expected, this.modbus.getConnectStatus());
    }

    private void thenTheReadRegistersAre(int... expected) {
        assertArrayEquals(expected, this.readRegisters);
    }

    private void thenTheReadBooleansAre(boolean... expected) {
        assertArrayEquals(expected, this.readBooleans);
    }

    private void thenTheSlaveRegisterIs(int address, int expected) {
        assertEquals(expected, this.slave.getRegister(address));
    }

    private void thenTheSlaveCoilIs(int address, boolean expected) {
        assertEquals(expected, this.slave.getCoil(address));
    }

    private void thenTheSlaveCoilsAreSetFrom(int address, int count) {
        for (int i = 0; i < count; i++) {
            assertTrue("coil " + (address + i) + " is not set", this.slave.getCoil(address + i));
        }
    }

    private static <T> T awaitService(final Class<T> clazz) {
        final long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(TIMEOUT_SECONDS);

        try {
            while (System.nanoTime() < deadline) {
                final Collection<ServiceReference<T>> references = bundleContext.getServiceReferences(clazz, null);
                if (!references.isEmpty()) {
                    return bundleContext.getService(references.iterator().next());
                }
                Thread.sleep(500);
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            fail("interrupted while waiting for the " + clazz.getSimpleName() + " service");
        } catch (Exception e) {
            fail("the " + clazz.getSimpleName() + " service could not be looked up: " + e.getMessage());
        }

        fail("no " + clazz.getSimpleName() + " service in " + TIMEOUT_SECONDS + " seconds");
        return null;
    }

}
