name: Kura SBOM upload

on:
  schedule:
    # At 00:00 on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
        target_branch:
          type: string
          default: 'develop'
          required: true
  workflow_run:
    workflows: ["Release Notes automation"]
    types:
      - completed

permissions:
  contents: read
  packages: read

jobs:
  call-workflow-in-public-repo:
    uses: eclipse-kura/.github/.github/workflows/_shared-sbom-cyclonedx.yml@main
    with:
      dependency-track-id: '88b926a2-2d26-4262-ae4d-0dd69a66f4ac'
